- name: Load distribution-specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- block:
    - ansible.builtin.include_tasks: system/pre-tasks.yml
    - ansible.builtin.include_tasks: system/cleanup.yml
    - ansible.builtin.include_tasks: system/repositories.yml
    - ansible.builtin.include_tasks: system/utilities.yml
    - ansible.builtin.include_tasks: system/services.yml
    - ansible.builtin.include_tasks: system/codecs.yml
    - ansible.builtin.include_tasks: system/zsh.yml
    - ansible.builtin.include_tasks: system/fonts.yml
    - ansible.builtin.include_tasks: system/wacom.yml

    ## GNOME
    - ansible.builtin.include_tasks: gnome/appearance.yml
    - ansible.builtin.include_tasks: gnome/datetime.yml
    - ansible.builtin.include_tasks: gnome/display.yml
    - ansible.builtin.include_tasks: gnome/extensions.yml
    - ansible.builtin.include_tasks: gnome/keyboard.yml
    - ansible.builtin.include_tasks: gnome/plugins.yml
    - ansible.builtin.include_tasks: gnome/tweaks.yml

    ## Software
    - ansible.builtin.import_tasks: software/audacity.yml
    - ansible.builtin.import_tasks: software/bitwarden.yml
    - ansible.builtin.import_tasks: software/boxes.yml
    - ansible.builtin.import_tasks: software/calibre.yml
    - ansible.builtin.import_tasks: software/chrome.yml
    - ansible.builtin.import_tasks: software/darktable.yml
    - ansible.builtin.import_tasks: software/deadbeef.yml
    - ansible.builtin.import_tasks: software/displaycal.yml
    - ansible.builtin.import_tasks: software/dropbox.yml
    - ansible.builtin.import_tasks: software/emacs.yml
    - ansible.builtin.import_tasks: software/filezilla.yml
    - ansible.builtin.import_tasks: software/flacon.yml
    - ansible.builtin.import_tasks: software/flatseal.yml
    - ansible.builtin.import_tasks: software/gimp.yml
    - ansible.builtin.import_tasks: software/inkscape.yml
    - ansible.builtin.import_tasks: software/kdenlive.yml
    - ansible.builtin.import_tasks: software/kid3.yml
    - ansible.builtin.import_tasks: software/libreoffice.yml
    - ansible.builtin.import_tasks: software/lollypop.yml
    - ansible.builtin.import_tasks: software/menulibre.yml
    - ansible.builtin.import_tasks: software/obs.yml
    - ansible.builtin.import_tasks: software/opera.yml
    - ansible.builtin.import_tasks: software/simplenote.yml
    - ansible.builtin.import_tasks: software/skype.yml
    - ansible.builtin.import_tasks: software/spotify.yml
    - ansible.builtin.import_tasks: software/teamviewer.yml
    - ansible.builtin.import_tasks: software/telegram.yml
    - ansible.builtin.import_tasks: software/thunderbird.yml
    - ansible.builtin.import_tasks: software/transmission.yml
    - ansible.builtin.import_tasks: software/vice.yml
    - ansible.builtin.import_tasks: software/vlc.yml
    - ansible.builtin.import_tasks: software/vokoscreen.yml
    - ansible.builtin.import_tasks: software/vscode.yml
    - ansible.builtin.import_tasks: software/xournalpp.yml
    - ansible.builtin.import_tasks: software/zoom.yml

    - ansible.builtin.include_tasks: system/post-tasks.yml
