- name: devel | download golang tarball
  become_user: zoliky
  get_url:
    url: "https://golang.org/dl/go1.15.6.linux-amd64.tar.gz"
    dest: ~/Downloads/
    mode: '0755'

- name: devel | install golang
  unarchive:
    src: /home/zoliky/Downloads/go1.15.6.linux-amd64.tar.gz
    dest: /usr/local