- name: GNOME | Appearance | Copy wallpapers
  ansible.builtin.copy:
    src: wallpapers/
    dest: /home/zoliky/Pictures/
    mode: 0644

- name: GNOME | Appearance | Set wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///home/zoliky/Pictures/0004.jpg'"

- name: GNOME | Appearance | Set wallpaper position
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
