- name: GNOME | Extensions | Install extension manager app
  community.general.flatpak:
    name: org.gnome.Extensions
    method: user
    state: present
  when: ansible_facts['distribution'] == "Fedora"

- name: GNOME | Extensions | Install GNOME extensions
  become: true
  ansible.builtin.package:
    name:
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-no-overview
    state: present
  when: ansible_facts['distribution'] == "Fedora"
