- name: GNOME | Extensions | Install extension manager app
  community.general.flatpak:
    name: org.gnome.Extensions
    method: user
    state: present
  when: ansible_facts['distribution'] == "Fedora"
