- name: GNOME | Plugins | Enable Flatpak in GNOME Software
  become: true
  ansible.builtin.package:
    name: gnome-software-plugin-flatpak
    state: present
  when: ansible_facts['distribution'] == "Debian"
