- name: GNOME | Tweaks | Disable hot corners
  community.general.dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "false"

- name: GNOME | Tweaks | Enable all window buttons
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"
