- name: software | emacs
  package:
    name: emacs
    state: present
  when: ansible_distribution == 'Fedora'

- name: software | emacs | mu4e
  package:
    name:
      - maildir-utils
      - isync
    state: present
  when: ansible_distribution == 'Fedora'

- name: software | emacs | hunspell
  package:
    name:
      - hunspell
      - hunspell-en-US
      - hunspell-hu
      - hunspell-ro
    state: present
  when: ansible_distribution == 'Fedora'