- name: Software | Emacs
  become: true
  ansible.builtin.package:
    name: emacs
    state: present
  when: ansible_distribution == 'Fedora'

- name: Software | Emacs | Install maildir-utils and isync
  become: true
  ansible.builtin.package:
    name:
      - maildir-utils
      - isync
    state: present
  when: ansible_distribution == 'Fedora'

- name: Software | Emacs | Install hunspell
  become: true
  ansible.builtin.package:
    name:
      - hunspell
      - hunspell-en-US
      - hunspell-hu
      - hunspell-ro
    state: present
  when: ansible_distribution == 'Fedora'
