- name: Software | Emacs | Install maildir-utils
  become: true
  ansible.builtin.package:
    name: maildir-utils
    state: present
  when: ansible_facts['distribution'] == "Fedora"

- name: Software | Emacs | Install isync
  become: true
  ansible.builtin.package:
    name: isync
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Software | Emacs | Install hunspell
  become: true
  ansible.builtin.package:
    name:
      - hunspell
      - hunspell-en-US
      - hunspell-hu
      - hunspell-ro
    state: present
  when: ansible_facts['os_family'] == "RedHat"
