- name: Software | LibreOffice
  become: true
  ansible.builtin.apt:
    name: libreoffice
    state: latest
    default_release: bookworm-backports
    update_cache: true
  when: ansible_facts['distribution'] == "Debian"
