- name: software | opera
  tags: software,opera
  dnf:
    disable_gpg_check: yes
    name: https://download3.operacdn.com/pub/opera/desktop/87.0.4390.45/linux/opera-stable_87.0.4390.45_amd64.rpm
    state: present
  when: ansible_distribution == 'Fedora'