- name: Software | TeamViewer
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
    state: present
  when: ansible_distribution == 'Fedora'
