- name: Software | TeXLive
  become: true
  ansible.builtin.package:
    name:
      - texlive-scheme-medium
      - texlive-capt-of
      - texlive-nopageno
    state: present
  when: ansible_facts['distribution'] == "Fedora"

- name: Software | Debian | TeXLive
  become: true
  ansible.builtin.package:
    name:
      - texlive
      - texlive-xetex
      - texlive-science
      - texlive-humanities
      - texlive-fonts-extra
      - texlive-lang-english
      - texlive-lang-european
    state: present
  when: ansible_facts['distribution'] == "Debian"
