- name: software | vscode | enable vscode repository
  yum_repository:
    file: vscode
    name: code
    enabled: yes
    gpgcheck: yes
    description: Visual Studio Code
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    baseurl: https://packages.microsoft.com/yumrepos/vscode
  when: ansible_distribution == 'Fedora'

- name: software | vscode | install vscode
  package:
    name: code
    state: present
  when: ansible_distribution == 'Fedora'