- name: System | Cleanup | Remove unwanted packages
  become: true
  ansible.builtin.apt:
    name:
      - cheese
      - gnome-games
      - gnome-music
      - gnome-sound-recorder
    purge: true
    autoremove: true
    state: absent
  when: ansible_facts['distribution'] == "Debian"
