- name: System | Cleanup | Remove unwanted packages
  become: true
  ansible.builtin.apt:
    name:
      - cheese
      - firefox-esr
      - gnome-games
      - gnome-music
      - gnome-sound-recorder
      - xserver-xorg-video-intel
    purge: true
    autoremove: true
    state: absent
  when: ansible_facts['distribution'] == "Debian"
