- name: System | Codecs | Install multimedia codecs
  become: true
  ansible.builtin.dnf:
    name: '@multimedia'
    allowerasing: true
    state: present
  when: ansible_facts['distribution'] == "Fedora"
