- name: System | Post-tasks | Clone dotfiles repository
  ansible.builtin.git:
    repo: "https://github.com/zoliky/dotfiles.git"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/dotfiles"

- name: System | Post-tasks | Copy dotfiles
  ansible.builtin.copy:
    src: "{{ lookup('ansible.builtin.env', 'HOME') }}/dotfiles/{{ item.src }}"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: "editorconfig", dest: ".editorconfig" }
    - { src: "gitconfig", dest: ".gitconfig" }
    - { src: "mbsyncrc", dest: ".mbsyncrc" }
    - { src: "zshenv", dest: ".zshenv" }
    - { src: "zshrc", dest: ".zshrc" }
    - { src: "kitty.conf", dest: ".config/kitty/kitty.conf" }
    - { src: "mpv.conf", dest: ".config/mpv/mpv.conf" }
