- name: System | Repositories | Add Flathub remote
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: user

- name: System | Repositories | Add CRB repository
  become: true
  ansible.builtin.command:
    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms
  when: ansible_facts['distribution'] == "RedHat"

- name: System | Repositories | Add EPEL GPG key
  become: true
  ansible.builtin.rpm_key:
    key: "{{ epel_gpg_key }}"
    state: present
  when: ansible_facts['distribution'] == "RedHat"

- name: System | Repositories | Add EPEL repository
  become: true
  ansible.builtin.dnf:
    name: "{{ epel_repository }}"
    state: present
  when: ansible_facts['distribution'] == "RedHat"

- name: System | Repositories | Add RPM Fusion GPG keys
  become: true
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  loop:
    - "{{ rpmfusion_free_gpg_key }}"
    - "{{ rpmfusion_nonfree_gpg_key }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: System | Repositories | Add RPM Fusion repositories
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ rpmfusion_free_repository }}"
    - "{{ rpmfusion_nonfree_repository }}"
  when: ansible_facts['os_family'] == "RedHat"
