- name: System | Repositories | Add Flathub remote
  tags: system,repository,flatpak
  become_user: zoliky
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: user

- name: System | Repositories | Add RPM Fusion GPG keys
  tags: system,repository,rpmfusion
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  loop:
    - "{{ rpmfusion_free_gpg_key }}"
    - "{{ rpmfusion_nonfree_gpg_key }}"
  when: ansible_distribution == 'Fedora'

- name: System | Repositories | Add RPM Fusion repositories
  tags: system,repository,rpmfusion
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ rpmfusion_free_repository }}"
    - "{{ rpmfusion_nonfree_repository }}"
  when: ansible_distribution == 'Fedora'
