- name: system | repositories | add flathub remote
  tags: system,repository,flatpak
  become_user: zoliky
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: user

- name: system | repositories | add rpmfusion free gpg key
  tags: system,repository,rpmfusion
  rpm_key:
    key: "{{ rpmfusion_free_gpg_key }}"
    state: present
  when: ansible_distribution == 'Fedora'

- name: system | repositories | add rpmfusion free
  tags: system,repository,rpmfusion
  dnf:
    name: "{{ rpmfusion_free_repository }}"
    state: present
  when: ansible_distribution == 'Fedora'

- name: system | repositories | add rpmfusion non-free gpg key
  tags: system,repository,rpmfusion
  rpm_key:
    key: "{{ rpmfusion_nonfree_gpg_key }}"
    state: present
  when: ansible_distribution == 'Fedora'

- name: system | repositories | add rpmfusion non-free free
  tags: system,repository,rpmfusion
  dnf:
    name: "{{ rpmfusion_nonfree_repository }}"
    state: present
  when: ansible_distribution == 'Fedora'