- name: System | Sleep | Create sleep.conf.d directory
  become: true
  ansible.builtin.file:
    path: /etc/systemd/sleep.conf.d
    state: directory
    mode: '0755'

- name: System | Sleep | Copy nosuspend.conf
  become: true
  ansible.builtin.template:
    src: nosuspend.conf.j2
    dest: /etc/systemd/sleep.conf.d/nosuspend.conf
    mode: '0644'
