- name: System | Utilities | Install utilities
  become: true
  ansible.builtin.package:
    name:
      - mpv
      - vim
      - dfc
      - htop
      - kitty
      - rsync
      - meson
      - neovim
      - ripgrep
    state: present
