- name: system | utilities | install utilities
  package:
    name:
      - mpv
      - vim
      - fzf
      - htop
      - meson
      - neovim
      - "{{ python_psutil_package }}"
    state: present