- name: System | Utilities | Install utilities
  become: true
  ansible.builtin.package:
    name:
      - mpv
      - vim
      - fzf
      - dfc
      - zip
      - curl
      - time
      - tmux
      - htop
      - kitty
      - rsync
      - meson
      - hdparm
      - neovim
      - gnupg2
      - ripgrep
      - neofetch
      - net-tools
      - distrobox
      - python3-gpg
    state: present

- name: System | Utilities | Install ufw
  become: true
  ansible.builtin.package:
    name: ufw
    state: present
  when: ansible_facts['distribution'] == "Debian"

- name: System | Utilities | Install yt-dlp
  become: true
  ansible.builtin.apt:
    name: yt-dlp
    state: latest
    default_release: bookworm-backports
    update_cache: true
  when: ansible_facts['distribution'] == "Debian"
