- name: System | Utilities | Install utilities
  become: true
  ansible.builtin.package:
    name:
      - mpv
      - vim
      - dfc
      - curl
      - htop
      - kitty
      - rsync
      - meson
      - neovim
      - ripgrep
    state: present

- name: System | Utilities | Install fzf
  become: true
  ansible.builtin.package:
    name: fzf
    state: present
  when: ansible_facts['distribution'] != "RedHat"
