- name: System | Utilities | Install utilities
  become: true
  ansible.builtin.package:
    name:
      - mpv
      - vim
      - fzf
      - dfc
      - htop
      - meson
      - neovim
      - ripgrep
      - "{{ python_psutil_package }}"
    state: present
