- name: system | wacom | copy xorg-hotplug
  copy:
    src: wacom/xorg-hotplug
    dest: /usr/local/bin/
    mode: 0755

- name: system | wacom | create autostart directory
  become_user: zoliky
  file:
    path: /home/zoliky/.config/autostart
    state: directory
    mode: 0755

- name: system | wacom | copy wacom.desktop
  copy:
    src: wacom/wacom.desktop
    dest: /home/zoliky/.config/autostart/
    mode: 0644