- name: System | Wacom | Copy xorg-hotplug
  become: true
  ansible.builtin.copy:
    src: wacom/xorg-hotplug
    dest: /usr/local/bin/
    mode: '0755'

- name: System | Wacom | Copy wacom.desktop
  ansible.builtin.copy:
    src: wacom/wacom.desktop
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/autostart/"
    mode: '0644'
