- name: System | Wacom | Copy xorg-hotplug
  ansible.builtin.copy:
    src: wacom/xorg-hotplug
    dest: /usr/local/bin/
    mode: 0755

- name: System | Wacom | Create autostart directory
  become_user: zoliky
  ansible.builtin.file:
    path: /home/zoliky/.config/autostart
    state: directory
    mode: 0755

- name: System | Wacom | Copy wacom.desktop
  ansible.builtin.copy:
    src: wacom/wacom.desktop
    dest: /home/zoliky/.config/autostart/
    mode: 0644
