- name: System | Zsh
  become: true
  ansible.builtin.package:
    name: zsh
    state: present
  when: ansible_distribution == 'Fedora'

- name: System | Zsh | Set zsh as default shell
  become: true
  ansible.builtin.user:
    name: 'zoliky'
    shell: /usr/bin/zsh
  when: ansible_distribution == 'Fedora'

- name: System | Zsh | Check if oh-my-zsh exists
  ansible.builtin.stat:
    path: /home/zoliky/.oh-my-zsh
  register: oh_my_zsh_dir

- name: System | Zsh | Git clone oh-my-zsh
  ansible.builtin.command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git /home/zoliky/.oh-my-zsh'
  when: not oh_my_zsh_dir.stat.exists

- name: System | Zsh | Copy zshenv
  become_user: zoliky
  ansible.builtin.copy:
    src: dotfiles/zshenv
    dest: /home/zoliky/.zshenv
    mode: 0644

- name: System | Zsh | Copy zshrc
  become_user: zoliky
  ansible.builtin.copy:
    src: dotfiles/zshrc
    dest: /home/zoliky/.zshrc
    mode: 0644
